package com.example.cab302tailproject.model;

// No specific imports needed for this simple model unless you add Date/Timestamp objects later.
// If you re-add ResponseTimestamp to the DB and use java.sql.Timestamp, you'd import it here.

/**
 * Represents a student's response to a learning card.
 * This class is used to model data from the 'StudentCardResponse' database table.
 */
public class StudentCardResponse {
    private int responseID;
    private int studentID;
    private int materialID; // This is the ID of the learning card deck (Material)
    private String cardQuestion;
    private boolean isCorrect;
    private int classroomID;
    // If you decide to re-add ResponseTimestamp to the database schema,
    // you would add a field for it here, e.g.:
    // private java.sql.Timestamp responseTimestamp;

    /**
     * Constructor for creating a StudentCardResponse object.
     *
     * @param responseID The unique ID of the response (usually auto-generated by the database).
     * @param studentID The ID of the student who made the response.
     * @param materialID The ID of the learning card material/deck.
     * @param cardQuestion The text of the question on the card.
     * @param isCorrect True if the student's answer was correct, false otherwise.
     * @param classroomID The ID of the classroom the student was in when responding.
     */
    public StudentCardResponse(int responseID, int studentID, int materialID, String cardQuestion, boolean isCorrect, int classroomID) {
        this.responseID = responseID;
        this.studentID = studentID;
        this.materialID = materialID;
        this.cardQuestion = cardQuestion;
        this.isCorrect = isCorrect;
        this.classroomID = classroomID;
        // If you add responseTimestamp:
        // this.responseTimestamp = responseTimestamp;
    }

    // Getter methods

    public int getResponseID() {
        return responseID;
    }

    public int getStudentID() {
        return studentID;
    }

    public int getMaterialID() {
        return materialID;
    }

    public String getCardQuestion() {
        return cardQuestion;
    }

    public boolean isCorrect() {
        return isCorrect;
    }

    public int getClassroomID() {
        return classroomID;
    }

    // public java.sql.Timestamp getResponseTimestamp() { // If you add it
    //     return responseTimestamp;
    // }

    // Setter methods (optional, depending on if you need to modify objects after creation)

    public void setResponseID(int responseID) {
        this.responseID = responseID;
    }

    public void setStudentID(int studentID) {
        this.studentID = studentID;
    }

    public void setMaterialID(int materialID) {
        this.materialID = materialID;
    }

    public void setCardQuestion(String cardQuestion) {
        this.cardQuestion = cardQuestion;
    }

    public void setCorrect(boolean correct) {
        isCorrect = correct;
    }

    public void setClassroomID(int classroomID) {
        this.classroomID = classroomID;
    }

    // public void setResponseTimestamp(java.sql.Timestamp responseTimestamp) { // If you add it
    //    this.responseTimestamp = responseTimestamp;
    // }

    @Override
    public String toString() {
        return "StudentCardResponse{" +
                "responseID=" + responseID +
                ", studentID=" + studentID +
                ", materialID=" + materialID +
                ", cardQuestion='" + cardQuestion.substring(0, Math.min(cardQuestion.length(), 30)) + "..." + '\'' +
                ", isCorrect=" + isCorrect +
                ", classroomID=" + classroomID +
                '}';
    }
}
